[package]
name = "conlang"
version = "0.1.0"
authors = ["Arthur Goldman <arthur@goldman-tribe.org>"]
edition = "2018"

[dependencies]
nom = { version = "4.1", features = ["std", "verbose-errors"] }
rustyline = "3.0"
failure = { version = "0.1", features = ["derive"] }
